#!/bin/bash
echo "initializing linked directories ..."

if [[ ! -d /data/dns ]]; then
  mkdir -p /data/dns
  chown -R nobody:nobody /data/dns
fi

if [[ ! -d $CONSUL_CONFIG_DIR ]]; then
  mkdir -p $CONSUL_CONFIG_DIR
  chown -R nobody:nobody $CONSUL_CONFIG_DIR
fi

if [[ ! -d $CONSUL_DATA_DIR ]]; then
  mkdir -p $CONSUL_DATA_DIR
  chown -R nobody:nobody $CONSUL_DATA_DIR
fi

if [[ ! -d $NOMAD_CONFIG_DIR ]]; then
  mkdir -p $NOMAD_CONFIG_DIR
  chown -R nobody:nobody $NOMAD_CONFIG_DIR
fi

if [[ ! -d $NOMAD_DATA_DIR ]]; then
  mkdir -p $NOMAD_DATA_DIR
  chown -R nobody:nobody $NOMAD_DATA_DIR
fi
