#!/bin/bash
echo "initializing linked directories ..."
if [[ ! -d /data ]]; then
  mkdir -p /data
  chown -R nobody:nobody /data
fi

if [[ -d /data/repository ]]; then
  mkdir -p /home/nobody/.m2
  ln -s /data/repository /home/nobody/.m2/repository
fi
if [[ -d /data/gradle-workdir ]]; then
  mkdir -p /home/nobody/.gradle
  if [[ -d /data/gradle-workdir/caches ]]; then
    ln -s /data/gradle-workdir/caches /home/nobody/.gradle/caches
  fi
  if [[ -d /data/gradle-workdir/native ]]; then
    ln -s /data/gradle-workdir/native /home/nobody/.gradle/native
  fi
  if [[ -d /data/gradle-workdir/wrapper ]]; then
    ln -s /data/gradle-workdir/wrapper /home/nobody/.gradle/wrapper
  fi
fi

if [[ -d /data/.ssh ]]; then
  cp /data/.ssh/* /home/nobody/.ssh/
fi
if [[ -e /data/.gitconfig ]]; then
  cp /data/.gitconfig /home/nobody/
fi
chown nobody:nobody -R /home/nobody
