#!/bin/bash

source /usr/bin/config.shlib

if [[ "x$INSTANCE_NAME" == "x" ]]; then
  echo "Instance name not defined"
  exit -1
fi

if [[ "x$1" == "x" ]]; then
  echo "Slot not defined"
  exit -1
fi

function finish {
  if [[ -s /tmp/${SLOT_NAME}.pid ]]; then
    if (( $$ == $(cat /tmp/${SLOT_NAME}.pid) )); then
      rm /tmp/${SLOT_NAME}.pid
    fi
  fi
}

trap finish EXIT

SLOT_NAME=$1
echo $INSTANCE_NAME $SLOT_NAME

# kill previous instance
if [[ -s /tmp/$SLOT_NAME.pid ]]; then
  PID=$(cat /tmp/${SLOT_NAME}.pid)
  if kill $PID 2>/dev/null; then
    while s=`ps -p $PID -o s=` && [[ "$s" && "$s" != 'Z' ]]; do
      sleep 1
    done
  fi
fi

echo $$ > /tmp/${SLOT_NAME}.pid

SLOT_DIR=/data/instance-config/$INSTANCE_NAME/$SLOT_NAME
CONFIG_FILE=$SLOT_DIR/config
INSTANCE_ENVIRONMENT_FILE=/data/instance-config/$INSTANCE_NAME/environment
SLOT_ENVIRONMENT_FILE=/data/instance-config/$INSTANCE_NAME/$SLOT_NAME/environment

if [[ ! -d $SLOT_DIR ]]; then
  mkdir -p $SLOT_DIR 2>/dev/null
fi

if [[ -s $INSTANCE_ENVIRONMENT_FILE ]]; then
  source $INSTANCE_ENVIRONMENT_FILE
fi

if [[ -s $SLOT_ENVIRONMENT_FILE ]]; then
  source $SLOT_ENVIRONMENT_FILE
fi

configured=0
cd /home/
if [[ -s $CONFIG_FILE ]]; then
  SERVICE_NAME=$(config_get $CONFIG_FILE "SERVICE_NAME")
  SERVICE_BINARY=$(config_get $CONFIG_FILE "SERVICE_BINARY")
  SERVICE_PARAMETERS=$(config_get $CONFIG_FILE "SERVICE_PARAMETERS")
  if [[ "$SERVICE_NAME" != "__UNDEFINED__" ]]; then
    if [[ "x$SERVICE_NAME" != "x" ]]; then
      if [[ -e "/data/repository/$SERVICE_BINARY" ]]; then
        configured=1
        if [[ "$SERVICE_PARAMETERS" == "__UNDEFINED__" ]]; then
          SERVICE_PARAMETERS=""
        fi
        cp -f "/data/repository/$SERVICE_BINARY" /home/nobody/service-$SLOT_NAME.jar
        java $SERVICE_PARAMETERS -jar /home/nobody/service-$SLOT_NAME.jar
      fi
    fi
  fi
fi

if [[ configured -eq 0 ]]; then
  echo "$SLOT_NAME: No service. Waiting for configuration ..."
  inotifywait -r -t -1 -e create,delete,modify,close_write,move,attrib $SLOT_DIR
fi
