#!/bin/bash

source /usr/bin/config.shlib

if [[ "x$INSTANCE_NAME" == "x" ]]; then
  echo "Instance name not defined"
  exit -1
fi

if [[ "x$1" == "x" ]]; then
  echo "Slot not defined"
  exit -1
fi

function finish {
  if [[ -s /tmp/${SLOT_NAME}.pid ]]; then
    if (( $$ == $(cat /tmp/${SLOT_NAME}.pid) )); then
      rm /tmp/${SLOT_NAME}.pid
    fi
  fi
}

trap finish EXIT

SLOT_NAME=$1
echo $INSTANCE_NAME $SLOT_NAME

# kill previous instance
if [[ -s /tmp/$SLOT_NAME.pid ]]; then
  PID=$(cat /tmp/${SLOT_NAME}.pid)
  if kill -0 $PID; then
    if kill $PID 2>/dev/null; then
      while s=`ps -p $PID -o s=` && [[ "$s" && "$s" != 'Z' ]]; do
        sleep 1
      done
    fi
  fi
fi

echo $$ > /tmp/${SLOT_NAME}.pid

REPOSITORY_DIR=/data/repository
INSTANCE_CONFIG_DIR=/data/instance-config/$INSTANCE_NAME

SLOT_DIR=$INSTANCE_CONFIG_DIR/$SLOT_NAME
CONFIG_FILE=$SLOT_DIR/config

INSTANCE_ENVIRONMENT_FILE=$INSTANCE_CONFIG_DIR/environment
SLOT_ENVIRONMENT_FILE=$SLOT_DIR/environment

if [[ ! -d $SLOT_DIR ]]; then
  mkdir -p $SLOT_DIR 
fi

if [[ -s $INSTANCE_ENVIRONMENT_FILE ]]; then
  cat $INSTANCE_ENVIRONMENT_FILE
  source $INSTANCE_ENVIRONMENT_FILE
fi

if [[ -s $SLOT_ENVIRONMENT_FILE ]]; then
  cat $SLOT_ENVIRONMENT_FILE
  source $SLOT_ENVIRONMENT_FILE
fi

configured=0
if [[ -s $CONFIG_FILE ]]; then
  SERVICE_NAME=$(config_get $CONFIG_FILE "SERVICE_NAME")
  SERVICE_BINARY=$(config_get $CONFIG_FILE "SERVICE_BINARY")
  SERVICE_PARAMETERS=$(config_get $CONFIG_FILE "SERVICE_PARAMETERS")
  DELAY_BEFORE=$(config_get $CONFIG_FILE "DELAY_BEFORE")
  if [[ "$SERVICE_NAME" != "__UNDEFINED__" ]]; then
    if [[ "x$SERVICE_NAME" != "x" ]]; then
      if [[ -e "$REPOSITORY_DIR/$SERVICE_BINARY" ]]; then
        configured=1
        if [[ "$SERVICE_PARAMETERS" == "__UNDEFINED__" ]]; then
          SERVICE_PARAMETERS=""
        fi
        if [[ "$DELAY_BEFORE" == "__UNDEFINED__" ]]; then
          DELAY_BEFORE="0"
        fi
        mkdir -p $HOME/$SLOT_NAME
        cp -f "$REPOSITORY_DIR/$SERVICE_BINARY" $HOME/$SLOT_NAME/service-$SLOT_NAME.jar
        cd $HOME/$SLOT_NAME
        if [[ $DELAY_BEFORE -gt 0 ]]; then
          sleep $DELAY_BEFORE
        fi
        java $SERVICE_PARAMETERS -jar $HOME/$SLOT_NAME/service-$SLOT_NAME.jar &
        RUN_PID=$!
        echo $RUN_PID 1>&2
        ps $RUN_PID 1>&2
        inotifywait -r -t -1 -e create,delete,modify,close_write,move,attrib $SLOT_DIR
        if kill -0 $RUN_PID; then
          kill $RUN_PID
        fi
        exit 1
      fi
    fi
  fi
fi

if [[ configured -eq 0 ]]; then
  echo "$SLOT_NAME: No service. Waiting for configuration ..."
  inotifywait -r -t -1 -e create,delete,modify,close_write,move,attrib $SLOT_DIR
  exit 1
fi
