if [[ "$CASSANDRA_MAX_HEAP_SIZE" != "default" -a ! -z "$CASSANDRA_MAX_HEAP_SIZE" ]]; then
  MAX_HEAP_SIZE="$CASSANDRA_MAX_HEAP_SIZE"
fi
if [[ "$CASSANDRA_HEAP_NEWSIZE" != "default" -a ! -z "$CASSANDRA_HEAP_NEWSIZE" ]]; then
  HEAP_NEWSIZE="$CASSANDRA_HEAP_NEWSIZE"
fi
