#!/bin/bash
if [[ -s /data/dns/resolv.conf ]]; then
  if [[ ! -e /tmp/resolv-checkpoint ]]; then
    cat /data/dns/resolv.conf > /etc/resolv.conf
    echo "$(date -Iseconds) dns updated"
    touch /tmp/resolv.checkpoint
  elif [[ /data/dns/resolv.conf -nt /tmp/resolv.checkpoint ]]; then
    cat /data/dns/resolv.conf > /etc/resolv.conf
    echo "$(date -Iseconds) dns updated"
    touch /tmp/resolv.checkpoint
  fi
  touch /tmp/resolv.checkpoint
fi
