#!/bin/bash
echo "initializing linked directories ..."

if [[ ! -d /data ]]; then
  mkdir -p /data
  chown -R nobody:nobody /data
fi
if [[ ! -d /data/dns ]]; then
  mkdir -p /data/dns
  chown -R nobody:nobody /data/dns
fi
if [[ ! -d /data/instance-config ]]; then
  mkdir -p /data/instance-config
  chown -R nobody:nobody /data/instance-config
fi
if [[ ! -d /data/repository ]]; then
  mkdir -p /data/repository
  chown -R nobody:nobody /data/repository
fi
if [[ -d /data/repository ]]; then
  mkdir -p /home/nobody/.m2
  ln -s /data/repository /home/nobody/.m2/repository
fi
chown nobody:nobody -R /home/nobody
